pipeline {
   agent {
	 docker {
		image 'openjdk:17-jdk-slim'
          }
        }
  
    stages {
	stage('compile'){
           steps {
              sh 'Javac Hello.java'
       }
    }
         stage('run'){
              steps{
                sh 'Java Hello'
       }
    }
  } 
}
