pipeline {
   agent {
	 docker {
		image 'openjdk:17-jdk-slim'
          }
        }
  
    stages {
        stage('debug'){
            steps {
               sh 'ls -la'
             }
         }
	stage('compile'){
           steps {
              sh 'javac Hello.java'
       }
    }
         stage('run'){
              steps{
                sh 'java Hello'
       }
    }
  } 
}
